name: build-experiment
on:
  push:
  schedule:
    - cron: '0 0 * * *' #every day at midnight

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      # Checkout push to registry action github repo
      - name: Checkout push to registry action
        uses: actions/checkout@v2

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: experiment
          tags: latest ${{ github.sha }}
          oci: true

      # Push the image to the GHCR
      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"

